feature(LT-31): add auth provider and authorization HOC? fix some bus…
SerpRus/battle-ship pull request #22
Opened 2023-11-03 06:32 UTC by mementocodum

… and styles, add signup api

### Какую задачу решаем
Авторизация должна проверяться через отдельно написанный Hook или HOC

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-03 15:32 UTC, lirioblanko approved these changes

2023-11-05 19:44 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Отлично постарались!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-11-05 19:44 UTC, IvanPeleshok commented on packages/client/src/app/providers/AuthProvider/AuthProvider.tsx
> +    const configAxios: AxiosRequestConfig = {
Предлагаю вынести обращение к апи в отдельный модуль
Для конфигурации axios предлагаю воспользоваться https://axios-http.com/ru/docs/instance и использовать уже настроенный baseUrl / withCredentials и т.д для работы с axios

Далее можем реализовать методы внутри компонента следующим образом:
```
const checkIsAuth = async () => {
  try {
    setIsLoading(true);
    const response = await api.getUser()
    setIsLoading(false);
    setUser(response.data);
    setIsAuth(true);
  } catch (error) {
    const errorMessage = JSON.parse(error.request.response);
    setErrors([errorMessage?.reason]);
  } finally {
    setIsLoading(false);
  }
}
```
Аналогично другие методы переписать

2023-11-05 19:44 UTC, IvanPeleshok commented on packages/client/src/pages/LoginPage/ui/loginPage.tsx
> +      .then(res => {
Предлагаю пользоваться async / await + try / catch
Так код будет читабельнее

2023-11-05 19:44 UTC, IvanPeleshok commented on packages/client/src/pages/RegistrationPage/ui/registrationPage.tsx
> +      toast.success('Пользователь создан успешно');
Где-то используется английская локаль, где-то на русском
Предлагаю привести к одному виду

2023-11-05 19:44 UTC, IvanPeleshok commented on packages/client/src/app/providers/AuthProvider/AuthProvider.tsx
> +  const value = useMemo(
Данные значения можно использовать из стора, асинхронные запросы через санки (рекомендация)
Так было бы проще и оптимизирование, т.к писать такие конструкции через контекст реакта - выстрел в ногу по производительности, если имплементация неправильная

2023-11-06 19:31 UTC, IvanPeleshok approved these changes
Здорово постарались!

Поздравляю, работа принята!

Хорошего дня :)

2023-11-07 05:11 UTC, merged