LT-41: Добавить OAuth-авторизацию в проект
SerpRus/battle-ship pull request #47
Opened 2023-12-04 14:47 UTC by mkpankratov

Ожидания:
Есть возможность авторизации через Yandex OAuth.

Пояснение:
После авторизации будет происходить редирект на страницу с вашим проектом. Чтобы ссылка заработала, отправьте её вашему ментору с просьбой добавить в OAuth. Если тестируете проект локально, в качестве redirect_uri можно использовать http://localhost:3000/ (без слеша в конце, это важно). Ещё варианты портов: 5000, 9000. Если ваш проект локально использует другой порт и по какой-то причине вам нужен именно он, обратитесь к ментору.

Комментарий: 
При успешной авторизации вылетает одна ошибка "Cookie is invalid", что является ожидаемым поведением с React Strict.

2023-12-04 19:34 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-12-04 19:34 UTC, IvanPeleshok commented on packages/client/src/app/providers/OAuth/helpers/getClientId.ts
> +  const result = await AxiosInstance<TGetClientId>(config);
А если запрос закончится реджектом промиса?
Предлагаю обработать данный сценарий с помощью try / catch

2023-12-04 19:34 UTC, IvanPeleshok commented on packages/client/src/pages/HomePage/ui/homePage.tsx
> +  useOAuth(dispatch);
Необязательно прокидывать dispatch агрументом, его можно получить внутри кастомного хука c помощью useDispatch

2023-12-05 07:22 UTC, SerpRus approved these changes

2023-12-05 13:20 UTC, mkpankratov commented on packages/client/src/app/providers/OAuth/helpers/getClientId.ts
> +  const result = await AxiosInstance<TGetClientId>(config);
Сделал.

2023-12-05 13:20 UTC, mkpankratov commented on packages/client/src/pages/HomePage/ui/homePage.tsx
> +  useOAuth(dispatch);
Да, сделал.

2023-12-05 19:40 UTC, IvanPeleshok approved these changes
Работа не имеет критических замечаний

Апрув!

2023-12-09 11:28 UTC, merged