Feature/lt 47. 8. Реализовать API для форума
SerpRus/battle-ship pull request #48
Opened 2023-12-05 07:13 UTC by SerpRus

### Какую задачу решаем
https://linear.app/lazy-team/issue/LT-47/8-realizovat-api-dlya-foruma
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-10 14:38 UTC, shoshinpuro approved these changes
Всё хорошо! модели написаны отлично! Работает как нужно

2023-12-11 16:18 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-12-11 16:18 UTC, IvanPeleshok commented on packages/server/app/routes/index.ts
> +    res.json('OK');
Статус создания ресурса - 201
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/201

2023-12-11 16:18 UTC, IvanPeleshok commented on packages/server/app/routes/index.ts
> +    const topic = await getTopicById(id);
Если промис вернёт реджект, то исключение будет прокинуто наружу и пользователь не получит ответт от сервера

Предлагаю обработать этот кейс с помощью try / catch (и ниже)

2023-12-11 19:29 UTC, SerpRus commented on packages/server/app/routes/index.ts
> +    const topic = await getTopicById(id);
Да, спасибо за верное замечание, я думал по поводу этой обработки ошибок, но когда реализовывал вылетело из головы)

2023-12-11 19:31 UTC, SerpRus commented on packages/server/app/routes/index.ts
> +    res.json('OK');
Сделал вот так, res.status(201).end();
Не уверен, правильно ли, но в network статус стал 201

2023-12-11 19:59 UTC, IvanPeleshok commented on packages/server/app/routes/index.ts
> +      console.error(e);
Предлагаю в таком случае не логировать ошибку, а отправлять ответ с каким-то информационным сообщением и статусом ответа 500

2023-12-11 20:00 UTC, IvanPeleshok requested changes
Предлагаю доработать ответ сервера, если возникло исключение при работе с ответом

2023-12-11 20:35 UTC, SerpRus commented on packages/server/app/routes/index.ts
> +      console.error(e);
Понял, спасибо, сейчас сделаю

2023-12-12 08:16 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув!

2023-12-12 12:02 UTC, SerpRus commented
> Всё замечательно, апрув!

Большое спасибо за указания на ошибки и помощь в их исправлении!

2023-12-12 12:05 UTC, merged