Lt 40
SerpRus/battle-ship pull request #50
Opened 2023-12-06 17:07 UTC by lirioblanko

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-07 19:11 UTC, mementocodum approved these changes

2023-12-07 19:52 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

По работе есть небольшие замечания, предлагаю доработать

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-12-07 19:52 UTC, IvanPeleshok commented on packages/server/index.ts
> +      const store = createStore({
Предлагаю вынести получение предзагруженного состояния вынести в отдельный модуль

В данном же модуле оставить
```
const store = getState()
const stateHtml = `<script>window.__PRELOADED_STATE__=${JSON.stringify(
  state
).replace(/</g, '\\u003c')}</script>`;
```

2023-12-07 19:52 UTC, IvanPeleshok commented on packages/server/index.ts
> +        user: {
Есть ли возможность сделать запрос за данными к пользователю на стороне сервера, чтобы это не моковые данные?

2023-12-07 21:32 UTC, lirioblanko commented on packages/server/index.ts
> +      const store = createStore({
ок, взяла на заметку
горящие сроки..

2023-12-07 21:32 UTC, lirioblanko commented on packages/server/index.ts
> +        user: {
Благодарю за рекомендацию, да, реализуем в дальнейшей работе
Сейчас срок поджимает, до воскресенья нужно закрыть еще один спринт
Если это не критичный момент, добавила TODO

2023-12-08 20:23 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Будет здорово, если всё-же в итоге реализуете тех.долг

Хорошего дня :)

2023-12-13 19:56 UTC, merged